title: GREK 101 01
baseurl: 'GREK101-F21/'
url: 'https://libatique.info/'

footer_content: "All material developed by Daniel Libatique and Neel Smith, and available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a>"

aux_links:
  "GREK 101 Github":
    - "https://github.com/dlibatique/GREK101-F21"

plugins:
  - bundler
  - jekyll
  - github-pages
  - rake
